name: build-and-test-linux

run-name: "Test Linux: Push ${{ github.event.after }} by ${{ github.actor }}" 
on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nuke-version: ["13.2v4"]
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Install Nuke
      run: |
          mkdir nuke-install
          wget -c https://thefoundry.s3.amazonaws.com/products/nuke/releases/${{ matrix.nuke-version }}/Nuke${{ matrix.nuke-version }}-linux-x86_64.tgz -O - | tar -xz ./nuke-install
          mkdir nuke
          sudo ./nuke-install/Nuke${{ matrix.nuke-version }}-linux-x86_64.run --accept-foundry-eula --prefix=./nuke
    - name: Get cmake
      uses: lukka/get-cmake@latest
    - name: Check Nuke 
      run: | 
          cd /nuke
          ls