name: build-and-test-MacOS

run-name: "Build MacOS: Push ${{ github.event.after }} by ${{ github.actor }}" 
on: [push]

jobs:
  build:
    name: Build DeepC Plugin for Nuke
    runs-on: macos-latest
    strategy:
      matrix:
        nuke-version: ["12.2v11", "13.0v10", "13.1v5", "13.2v8", "14.0v6", "14.1v1"]
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Install Nuke
      run: |
          mkdir nuke
          curl  https://thefoundry.s3.amazonaws.com/products/nuke/releases/${{ matrix.nuke-version }}/Nuke${{ matrix.nuke-version }}-mac-x86_64.dmg -o Nuke${{ matrix.nuke-version }}-mac-x86_64.dmg
          echo "Installing Nuke"
          hdiutil convert Nuke${{ matrix.nuke-version }}-mac-x86_64.dmg -format UDTO -o temp.cdr
          hdiutil attach temp.cdr
          pushd /Volumes/Nuke${{ matrix.nuke-version }}-mac-x86_64
          echo "Copying Nuke"
          cp -R Nuke${{ matrix.nuke-version }} ${{ github.workspace }}/nuke/
          popd
          ls ${{ github.workspace }}/nuke/Nuke${{ matrix.nuke-version }}/Nuke${{ matrix.nuke-version }}.app/Contents/MacOS
    - name: Get cmake
      uses: lukka/get-cmake@latest
    - name: Build DeepC for Nuke 
      run: | 
          mkdir build
          mkdir install
          cmake -S . -DCMAKE_INSTALL_PREFIX="./install" -DNuke_ROOT="${{ github.workspace }}/nuke/Nuke${{ matrix.nuke-version }}/Nuke${{ matrix.nuke-version }}.app/Contents/MacOS" -B "build"
          cmake --build "build" --config Release
          cmake --install "build"
    - name: Compress files
      run:  zip -r DeepC-MacOS-Nuke${{ matrix.nuke-version }}.zip ./install
    - name: Upload Deep artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: DeepC-MacOS-Nuke${{ matrix.nuke-version }}
        path: "DeepC-*.zip"
