name: build-and-test-Windows

run-name: "Build Windows: Push ${{ github.event.after }} by ${{ github.actor }}" 
on: [push]

jobs:
  build:
    name: Build DeepC Plugin for Nuke
    runs-on: windows-latest
    strategy:
      matrix:
        nuke-version: ["13.2v4"]
        #nuke-version: ["12.0v8", "12.1v5", "12.2v11", "13.0v10", "13.1v5", "13.2v4"]
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Download Nuke
      shell: pwsh
      run: |
          mkdir nuke-install
          curl https://thefoundry.s3.amazonaws.com/products/nuke/releases/${{ matrix.nuke-version }}/Nuke${{ matrix.nuke-version }}-win-x86_64.zip -O ./nuke.zip
          Expand-Archive -Force ./nuke.zip ./nuke-install
          cd nuke-install
          ls
    - name: Install Nuke
      run: |
          mkdir nuke
          ./nuke-install/Nuke${{ matrix.nuke-version }}-win-x86_64 /S /ACCEPT-FOUNDRY-EULA /D=./Nuke
    #- name: Install OpenGL and Glu
    #  run: | 
    #      sudo apt-get update
    #      sudo apt-get install build-essential libgl1-mesa-dev libglu1-mesa-dev
    - name: Get cmake
      uses: lukka/get-cmake@latest
    - name: Build DeepC for Nuke 
      run: | 
          mkdir build
          mkdir install
          cmake -S . -DCMAKE_INSTALL_PREFIX="./install" -DNuke_ROOT="./nuke/Nuke${{ matrix.nuke-version }}" -B "build"
          cmake --build "build" --config Release
          cmake --install "build"
    - name: Compress files
      shell: pwsh
      run:  Compress-Archive -LiteralPath "./install" -DestinationPath "./DeepC-Windows-Nuke${{ matrix.nuke-version }}.zip" -Force
    - name: Upload Deep artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: DeepC-Windows-Nuke${{ matrix.nuke-version }}
        path: "DeepC-*.zip"